/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Clases.EjecutarQuery;
import Clases.LlenarTabla;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author aazañero
 */
public class Man_Facturas extends javax.swing.JFrame {

    /**
     * Creates new form NotaCredito
     */
    public Man_Facturas() {
        initComponents();
        Clases.Conecx con = new Clases.Conecx();
        Statement sql = null;

        try {
            sql = con.Conectarse().createStatement();
            String consulta = "SELECT Serie FROM Correlativos Where Estado='A' AND TipoDocumento IN ('01','03')";
            ResultSet rs = sql.executeQuery(consulta);
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Serie", "Numero", "Fecha emisión", "Cliente", "Importe Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, 318, 231));

        jLabel1.setText("Facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 104, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 74, 155, -1));

        jLabel2.setText("Serie");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        jLabel3.setText("Numero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 40, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 102, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "ImporteItem"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 174, 306, 231));

        jLabel4.setText("Detalle");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 152, -1, -1));

        jButton2.setText("Anular factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Selecciones un Item","IVAN ARIAS","DIANA BOCANEGRA"}));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeVisible(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clases.Conecx con = new Clases.Conecx();
        Statement sql = null;
        String serie = (String) jComboBox1.getSelectedItem();
        String numero = jTextField1.getText();

        String consulta = "EXEC [dbo].[AF_MANAGE_FACTURAS] 1,'" + serie + "','" + numero + "'";
        //System.out.println(consulta);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        LlenarTabla lleno = new LlenarTabla();
        lleno.llenar(jTable1, consulta);
        /*try{
            PreparedStatement stw;
            int numer=Integer.parseInt(numero);
            sql = con.Conectarse().createStatement();
            ResultSet rs = sql.executeQuery(consulta);
            modelo.setRowCount(0);
            while(rs.next()){
                System.out.println("pase");
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                modelo.addRow(v);      
                jTable1.setModel(modelo);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Revisar Número de Factura");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error: " + ex.toString());
        }*/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        String numerobus = "", seriebus = "";
        int seleccion = -1;
        seleccion = jTable1.getSelectedRow();
        Clases.Conecx con = new Clases.Conecx();
        if (seleccion != -1) {
            numerobus = (String) jTable1.getValueAt(seleccion, 0);
            seriebus = (String) jTable1.getValueAt(seleccion, 1);
        }
        Statement sql = null;
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();

        numerobus = (String) jTable1.getValueAt(seleccion, 0);
        seriebus = (String) jTable1.getValueAt(seleccion, 1);

        try {
            String consulta = "EXEC [dbo].[AF_MANAGE_FACTURAS] 2,'" + numerobus + "','" + seriebus + "'";
            sql = con.Conectarse().createStatement();
            ResultSet rs = sql.executeQuery(consulta);
            modelo.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                modelo.addRow(v);
                jTable2.setModel(modelo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Statement sql = null;
        String autorizador = "";
        int seleccion = -1;
        seleccion = jTable1.getSelectedRow();
        autorizador = (String) jComboBox2.getSelectedItem();
        if (seleccion != -1) {
            if (autorizador.contains("Seleccione")) {
                JOptionPane.showMessageDialog(null, "Seleccione un autorizador");
            } else {
                String numerobus = (String) jTable1.getValueAt(seleccion, 0);
                String seriebus = (String) jTable1.getValueAt(seleccion, 1);
                try {
                    EjecutarQuery exec = new EjecutarQuery();
                    String consulta = "EXEC [dbo].[AF_MANAGE_FACTURAS] 4,'" + numerobus + "','" + seriebus + "'";
                    String id = exec.ejecutar(consulta);
                    //System.out.println(consulta);
                    //System.out.println(id);
                    switch (autorizador) {
                        case "IVAN ARIAS":
                            autorizador = "iarias";
                            break;
                        case "DIANA BOCANEGRA":
                            autorizador = "iarias";
                            break;
                        default:
                            autorizador = "otros";
                            break;
                    }
                    consulta = "EXEC [dbo].[AF_MANAGE_CCOBRAR] '2','','',''," + id + ",'" + autorizador + "'";
                    consulta = exec.ejecutar(consulta);
                    Clases.Conecx con = new Clases.Conecx();
                    consulta = "EXEC [dbo].[AF_MANAGE_FACTURAS] 3,'" + numerobus + "','" + seriebus + "'";
                    sql = con.Conectarse().createStatement();
                    ResultSet rs = sql.executeQuery(consulta);
                    while (rs.next()) {
                        JOptionPane.showMessageDialog(null, "" + rs.getString(1));
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeVisible
        jComboBox2.removeItem("Selecciones un Item");
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Man_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Man_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Man_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Man_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Man_Facturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
