/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import Clases.EnviarCorreo;
import java.io.File;
import Clases.ExcelAdapter;
import Clases.PegarExcel;
import Clases.VerificarCodigos;
import java.beans.Statement;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aazañero
 */
public class MigracionVentas extends javax.swing.JFrame {

    /**
     * Creates new form MigracionVentas
     */
    public MigracionVentas() {
        initComponents();
        
        PegarExcel myAd1 = new PegarExcel(jTable1);
        PegarExcel myAd2 = new PegarExcel(jTable2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 225, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("CABECERA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serie", "Numero", "Fecha", "RUC", "Nom.Cliente", "Direc.Cliente", "Distrito", "Provincia", "Moneda", "TC", "Base Imponible", "IGV", "Total", "Estado", "PreparadoPor", "PreparadoEl", "Guia", "Vendedor", "ModalidadVenta", "Pedido", "FechaVenc"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Migrar Cabecera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 360));

        jPanel2.setBackground(new java.awt.Color(213, 225, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("DETALLE");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Factura", "Codigo", "Cantidad", "Precio_unit", "Subtotal", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Migrar Detalle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 620, 290));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contenido="";
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int filamodelo=jTable1.getRowCount();
        int filasusadas=0;
        String consulta="'", estado = "", preparadoel = "", moneda = "",
                fecha="",ruc="",razonsoc="",direcc="",distrito="",prov="",preparadopor="",
                guia="",modalidad="",nroped="",fechavenc="",vendedor="",tc="",bi="",igv="",total="";
    try{   
        Clases.Conecx con = new Clases.Conecx();
        for(int i=0;i<filamodelo;i++){
            fecha=(String)modelo.getValueAt(i,2);
            ruc=(String)modelo.getValueAt(i,3);
            razonsoc=(String)modelo.getValueAt(i,4);
            direcc=(String)modelo.getValueAt(i,5);
            distrito=(String)modelo.getValueAt(i,6);
            prov=(String)modelo.getValueAt(i,7);
            moneda=(String)modelo.getValueAt(i,8);
            tc=(String)modelo.getValueAt(i,9);
            bi=(String)modelo.getValueAt(i,10);
            igv=(String)modelo.getValueAt(i,11);
            total=(String)modelo.getValueAt(i,12);
            estado=(String)modelo.getValueAt(i,13);
            preparadopor=(String)modelo.getValueAt(i,14);
            preparadoel=(String)modelo.getValueAt(i,15);
            guia=(String)modelo.getValueAt(i,16);
            vendedor=(String)modelo.getValueAt(i,17);
            modalidad=(String)modelo.getValueAt(i,18);
            nroped=(String)modelo.getValueAt(i,19);
            fechavenc=(String)modelo.getValueAt(i,20);

            if(ruc.equals(" ")){
                ruc="-";
            }
            if(razonsoc.equals(" ")){
                razonsoc="-";
            }
            if(direcc.equals(" ")){
                direcc="-";
            }
            if(distrito.equals(" ")){
                distrito="-";
            }
            if(prov.equals(" ")){
                prov="-";
            }
            if(moneda.equals(" ")){
                moneda="USD";
            }
            if(tc.equals(" ")){
                tc="3.973";
            }
            if(bi.equals(" ")){
                bi="0.00";
            }
            if(igv.equals(" ")){
                igv="0.00";
            }
            if(total.equals(" ")){
                total="0.00";
            }
            if(estado.equals("send") || estado.equals("done") || estado.equals("generate")){
                estado="A";
            }
            if(preparadopor.equals(" ")){
                preparadopor="-";
            }
            if(preparadoel.equals(" ")){
                preparadoel=fecha;
            }
            if(guia.equals(" ")){
                guia="-";
            }
            if(vendedor.equals(" ")){
                vendedor="-";
            }
            if(modalidad.equals(" ")){
                modalidad="-";
            }
            if(nroped.equals(" ")){
                nroped="-";
            }
            if(fechavenc.equals(" ")){
                fechavenc="";
            }
            
            if(razonsoc.contains("'")){
                razonsoc=razonsoc.replaceAll("'","''");
            }
            
            if(modelo.getValueAt(i,0)!=null){
                filasusadas++;
                consulta = "EXEC [dbo].[JM_MANAGE_RVENTAS_CCOBRAR] '-','" + ((String)modelo.getValueAt(i,1)).substring(0,4) + "','" + ((String)modelo.getValueAt(i,1)).substring(6,13)
                            + "','" + fecha + "','" + ruc + "','" + razonsoc + "','" + direcc + "','" + distrito + "','" + prov + 
                            "','" + moneda + "'," + tc + "," + bi + "," + igv + "," + total + ",0.00,'" + estado + "','01/01/1900','-','-','" 
                            + preparadopor + "','" + preparadoel + "','" + guia + "','" + vendedor + "','" + modalidad + "',0.00," + bi + ",'-','" + nroped + "','" + fechavenc + "',0,'" + fechavenc + "'";
                java.sql.Statement sql = null;                
                System.out.println(consulta);

               sql = con.Conectarse().createStatement();
               ResultSet rs = sql.executeQuery(consulta);
               Instant instant = Instant.now();
               String fechaactual=instant.toString().substring(0,10);
               String user = System.getProperty("user.name");
               File directorios = new File("C:/Users/" + user + ".FESEPSA/Desktop/MigRegVentas" + fechaactual);
                if (!directorios.exists()) {
                    if (directorios.mkdirs()) {
                        System.out.println("Multiples directorios fueron creados");
                    } else {
                        System.out.println("Error al crear directorios");
                    }
                }
               FileWriter fichero = new FileWriter("C:/Users/" + user + ".FESEPSA/Desktop/MigRegVentas" + fechaactual + "/Log-RegVentas" + fechaactual + ".txt");
                    while(rs.next()){
                        System.out.println(rs.getString(1));
                        contenido=contenido+rs.getString(1)+"\n";
                    }
                    fichero.write(contenido);
                    fichero.close();
                    
            }else{
                break;
            }
            
        }
        JOptionPane.showMessageDialog(null,"Se realizó la migración de la Cabecera correctamente con " + jTable1.getRowCount() + " filas");
    }catch(java.lang.NullPointerException ex){
            System.out.println("Terminó de ejecutar la cabecera");
    }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error: " + ex.toString());
    }catch (IOException ex){
            Logger.getLogger(MigracionVentas.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String strcons="(",rpta="";
        
        VerificarCodigos ver = new VerificarCodigos();
        rpta=ver.ver(jTable2,1);
        //JOptionPane.showMessageDialog(null,rpta);
        if(rpta.contains("Faltan")){
            JOptionPane.showMessageDialog(null,"" + rpta);
        }
        if(rpta.contains("COMPLETOS")){
            JOptionPane.showMessageDialog(null,"" + rpta);
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            int filamodelo=jTable2.getRowCount();
            String contenido2="";
            try{   
                Clases.Conecx con = new Clases.Conecx();
                for(int i=0;i<filamodelo;i++){
                    int filasusadas=0;
                    String consulta="",doc="",codigo="",cant="",precio="",importebruto="",importeventa="";
                    if(modelo.getValueAt(i,0)!=null){
                        filasusadas++;
                        doc=((String)modelo.getValueAt(i,0)).replaceAll("-","");
                        codigo=(String)modelo.getValueAt(i,1);
                        cant=(String)modelo.getValueAt(i,2);
                        precio=(String)modelo.getValueAt(i,3);
                        importebruto=(String)modelo.getValueAt(i,4);
                        importeventa=(String)modelo.getValueAt(i,5);

                        if (precio.equals(" ")){
                            precio="0.00";
                        }
                        if (importebruto.equals(" ")){
                            importebruto="0.00";
                        }
                        if (importeventa.equals(" ")){
                            importeventa="0.00";
                        }


                        if(codigo.length()==5){
                            codigo="00" + codigo;
                        }

                        consulta = "EXEC [dbo].[JM_MANAGE_RVENTAS_DETALLE_COMBOS] '" + doc + "','" + codigo + "'," +cant + 
                                    "," + precio + "," + importebruto + "," + importebruto + "," + importeventa;
                        System.out.println(consulta); 
                        java.sql.Statement sql = null;                
                       Instant instant = Instant.now();
                       String fechaactual=instant.toString().substring(0,10);
                       String user = System.getProperty("user.name");
                       File directorios = new File("C:/Users/" + user + ".FESEPSA/Desktop/MigRegVentas" + fechaactual);
                        if (!directorios.exists()) {
                            if (directorios.mkdirs()) {
                                System.out.println("Multiples directorios fueron creados");
                            } else {
                                System.out.println("Error al crear directorios");
                            }
                        }
                       FileWriter fichero2 = new FileWriter("C:/Users/" + user + ".FESEPSA/Desktop/MigRegVentas" + fechaactual + "/Log-DetRegVentas" + fechaactual + ".txt");      
                       sql = con.Conectarse().createStatement();
                       ResultSet rs = sql.executeQuery(consulta);
                            while(rs.next()){
                                System.out.println(rs.getString(1));
                                //fichero2.write(rs.getString(1) +"\n");
                                contenido2=contenido2+rs.getString(1)+"\n";
                            }
                            fichero2.write(contenido2);
                            fichero2.close();
                            
                            
                            
                    }else{
                        break;
                    } 
                    
                }
                JOptionPane.showMessageDialog(null,"Se realizó la migración del Detalle correctamente con " + jTable2.getRowCount() + " filas");
                EnviarCorreo envio = new EnviarCorreo();        
                String fecha = (String)jTable1.getValueAt(0,2);
                envio.enviar("a.azanero@fesepsa.pe", "Registro de Facturas " + fecha, "Se realizó con éxito el registro de Facturas en SIGO.\nSaludos");
            }catch(java.lang.NullPointerException ex){
                    System.out.println("Terminó de ejecutar la cabecera");
            }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null,"Error: " + ex.toString());
            }catch (IOException ex){
                    Logger.getLogger(MigracionVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MenuSerio abrir = new MenuSerio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MigracionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MigracionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MigracionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MigracionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MigracionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
